#!/usr/bin/env bash
#
# scripts/rime.sh — install / configure / manage the RIME input method (on fcitx5) on Ubuntu.
#
# RIME (https://rime.im) is a highly-configurable input method engine for Chinese / CJK.
# On Ubuntu it rides on the fcitx5 input-method framework (the community-preferred carrier).
# This script is a *component manager* (like scripts/zsh.sh / scripts/tmux.sh): it installs
# fcitx5 + the RIME engine + frontends, selects the framework, writes the environment that
# lets apps talk to fcitx5, and manages which RIME schemas (输入方案) are enabled — with an
# opt-in for the popular 雾凇拼音 (rime-ice) config. Everything is user-space; only apt needs
# root (escalated per-command via the shared library), never whole-root, never `sudo npm`.
#
# Install channels: apt only (fcitx5 + RIME are in the official Ubuntu repos).
#
# Configuration model (mirrors scripts/ghostty.sh's managed drop-in):
#   - Preferences live in ~/.config/ubuntu-setup/rime.conf (the kit's KEY=VALUE store).
#   - From them we regenerate a managed RIME patch ~/.local/share/fcitx5/rime/default.custom.yaml
#     (we own it; rewritten wholesale + convergent; backed up before the first overwrite).
#   - The fcitx5 input-method environment is a managed file we own too:
#     ~/.config/environment.d/ubuntu-setup-rime.conf (GTK/QT/XMODIFIERS).
#   - A managed XDG autostart entry ~/.config/autostart/org.fcitx.Fcitx5.desktop launches
#     fcitx5 at login. This is REQUIRED on Wayland (Ubuntu's default): im-config/im-launch
#     only starts the IM daemon for X11 sessions (its Wayland branch is disabled) and the
#     fcitx5 package ships no /etc/xdg/autostart entry — so without it nothing starts fcitx5
#     and the desktop keeps falling back to its built-in IBus.
#   - Fuzzy pinyin (模糊音) is a *per-schema* speller/algebra feature, so it cannot live in
#     default.custom.yaml (that patches the GLOBAL default — schema_list/menu). Instead we
#     manage a small per-schema patch ~/.local/share/fcitx5/rime/<schema>.custom.yaml for each
#     enabled pinyin schema (rime_ice when 雾凇拼音 is active, else the luna_pinyin family),
#     appending the chosen fuzzy rules via 'speller/algebra/+' so we never have to reproduce a
#     schema's full algebra. We own only files carrying our marker; a user's own <schema>.custom
#     .yaml is backed up before we take it over, and our files are removed when fuzzy is cleared.
#
# Honesty note: RIME/fcitx5 is a *desktop* input method. Over SSH / on a headless server you
# are not running a graphical session on this box — these settings apply where the desktop
# actually runs (a machine with a display), and take effect after the next login. install /
# configure / deploy say so when they detect an SSH session or no display.
#
# Run it as:  rime.sh install|remove|configure|deploy|status|ui|meta|help   (or via `swkit`).

set -Eeuo pipefail

# Locate and load the shared library (scripts/ sits next to lib/ under the kit root).
_kit_here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=../lib/common.sh
source "$_kit_here/lib/common.sh"

# --- Curated knowledge ---------------------------------------------------------
readonly _RIME_ICE_REPO="https://github.com/iDvel/rime-ice.git"
# fcitx5-rime bundles rime-data (brise), so these schemas need no extra download.
readonly _RIME_CURATED=(
  luna_pinyin_simp luna_pinyin luna_pinyin_fluency
  double_pinyin_flypy double_pinyin bopomofo
  wubi86 wubi_pinyin cangjie5 stroke terra_pinyin
)

# Curated fuzzy-pinyin (模糊音) pairs. Each key maps (via _rime_fuzzy_rules) to one or more RIME
# `derive` rules that get appended to a pinyin schema's speller/algebra. These mirror the (commented)
# fuzzy block that rime-ice ships in rime_ice.schema.yaml, so enabling them here matches upstream.
readonly _RIME_FUZZY=(
  zh_z n_l f_h l_r g_k
  in_ing en_eng an_ang ian_iang uan_uang
)

# The full-pinyin schemas a fuzzy patch can target. Full pinyin only: double-pinyin schemas map
# keystrokes, not full-pinyin spellings, so these `derive` rules don't apply to them; non-pinyin
# schemas (wubi/cangjie/stroke/bopomofo) have no concept of 模糊音. We iterate this fixed set when
# converging/cleaning per-schema fuzzy files (so stale ones are removed when schemas change).
readonly _RIME_FUZZY_SCHEMAS=(
  luna_pinyin_simp luna_pinyin luna_pinyin_fluency terra_pinyin rime_ice
)

# First line of every fuzzy <schema>.custom.yaml we generate — lets us tell our files from a
# user's own (we only ever overwrite/remove a file whose first line carries this marker).
readonly _RIME_FUZZY_MARK='# Generated by ubuntu-setup (swkit rime)'

# fcitx5's GNOME-on-Wayland "self-diagnose" notification nags at EVERY login to install the
# kimpanel GNOME Shell extension (https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#GNOME).
# RIME works fine without kimpanel, so for most users it's pure noise. fcitx5 hides a tip
# permanently when its id is listed under [HiddenNotifications] in notifications.conf — exactly
# what its "Do not show again" button writes. This is that GNOME tip's id (see _rime_apply_diagnose_silence).
readonly _RIME_WAYLAND_DIAGNOSE_TIP='wayland-diagnose-gnome'

# Echo the RIME speller/algebra `derive` rule(s) for one fuzzy pair, one per line. Single-quoted
# so $1/$2/$ stay literal (they are RIME regex back-references, not shell expansions — that is the
# whole point here, so SC2016's "expressions don't expand in single quotes" note is expected).
# shellcheck disable=SC2016
_rime_fuzzy_rules() {
  case "$1" in
    zh_z)     printf '%s\n' 'derive/^([zcs])h/$1/' 'derive/^([zcs])([^h])/$1h$2/' ;;
    n_l)      printf '%s\n' 'derive/^n/l/' 'derive/^l/n/' ;;
    f_h)      printf '%s\n' 'derive/^f/h/' 'derive/^h/f/' ;;
    l_r)      printf '%s\n' 'derive/^l/r/' 'derive/^r/l/' ;;
    g_k)      printf '%s\n' 'derive/^g/k/' 'derive/^k/g/' ;;
    in_ing)   printf '%s\n' 'derive/in$/ing/' 'derive/ing$/in/' ;;
    en_eng)   printf '%s\n' 'derive/en$/eng/' 'derive/eng$/en/' ;;
    an_ang)   printf '%s\n' 'derive/an$/ang/' 'derive/ang$/an/' ;;
    ian_iang) printf '%s\n' 'derive/ian$/iang/' 'derive/iang$/ian/' ;;
    uan_uang) printf '%s\n' 'derive/uan$/uang/' 'derive/uang$/uan/' ;;
  esac
}

# One-line schema descriptions, localized (en/zh/ja). Same shape as scripts/tmux.sh's
# TMUX_I18N: schema *names* are never translated (project rule), only the gloss.
declare -gA RIME_I18N
RIME_I18N[en:luna_pinyin_simp]="Pinyin (朙月拼音) — simplified output"
RIME_I18N[en:luna_pinyin]="Pinyin (朙月拼音) — trad./simp. per dict"
RIME_I18N[en:luna_pinyin_fluency]="Sentence-flow Pinyin (语句流)"
RIME_I18N[en:double_pinyin_flypy]="Xiaohe double pinyin (小鹤双拼)"
RIME_I18N[en:double_pinyin]="Ziranma double pinyin (自然码)"
RIME_I18N[en:bopomofo]="Bopomofo / Zhuyin (注音)"
RIME_I18N[en:wubi86]="Wubi 86 (五笔)"
RIME_I18N[en:wubi_pinyin]="Wubi + Pinyin (五笔·拼音)"
RIME_I18N[en:cangjie5]="Cangjie 5 (仓颉)"
RIME_I18N[en:stroke]="Stroke order (五笔画)"
RIME_I18N[en:terra_pinyin]="Terra Pinyin with tones (地球拼音)"
RIME_I18N[zh:luna_pinyin_simp]="朙月拼音 · 简体输出"
RIME_I18N[zh:luna_pinyin]="朙月拼音 · 繁简随词库"
RIME_I18N[zh:luna_pinyin_fluency]="语句流(整句拼音)"
RIME_I18N[zh:double_pinyin_flypy]="小鹤双拼"
RIME_I18N[zh:double_pinyin]="自然码双拼"
RIME_I18N[zh:bopomofo]="注音"
RIME_I18N[zh:wubi86]="五笔 86"
RIME_I18N[zh:wubi_pinyin]="五笔·拼音混合"
RIME_I18N[zh:cangjie5]="仓颉五代"
RIME_I18N[zh:stroke]="五笔画(笔顺)"
RIME_I18N[zh:terra_pinyin]="地球拼音(带声调)"
RIME_I18N[ja:luna_pinyin_simp]="拼音(朙月)· 簡体字出力"
RIME_I18N[ja:luna_pinyin]="拼音(朙月)· 繁簡混在"
RIME_I18N[ja:luna_pinyin_fluency]="文流入力(整文拼音)"
RIME_I18N[ja:double_pinyin_flypy]="小鶴双拼"
RIME_I18N[ja:double_pinyin]="自然碼双拼"
RIME_I18N[ja:bopomofo]="注音"
RIME_I18N[ja:wubi86]="五筆 86"
RIME_I18N[ja:wubi_pinyin]="五筆・拼音混合"
RIME_I18N[ja:cangjie5]="倉頡五代"
RIME_I18N[ja:stroke]="筆画入力"
RIME_I18N[ja:terra_pinyin]="地球拼音(声調付き)"

# Fuzzy-pinyin pair glosses (en/zh/ja). The pinyin letters + ↔ are language-neutral; only the
# linguistic descriptor (flat/retroflex, front/back nasal…) is localized. Keys are never translated.
RIME_I18N[en:fz_zh_z]="zh ch sh ↔ z c s  (flat / retroflex)"
RIME_I18N[en:fz_n_l]="n ↔ l"
RIME_I18N[en:fz_f_h]="f ↔ h"
RIME_I18N[en:fz_l_r]="l ↔ r"
RIME_I18N[en:fz_g_k]="g ↔ k"
RIME_I18N[en:fz_in_ing]="in ↔ ing  (front / back nasal)"
RIME_I18N[en:fz_en_eng]="en ↔ eng  (front / back nasal)"
RIME_I18N[en:fz_an_ang]="an ↔ ang  (front / back nasal)"
RIME_I18N[en:fz_ian_iang]="ian ↔ iang"
RIME_I18N[en:fz_uan_uang]="uan ↔ uang"
RIME_I18N[zh:fz_zh_z]="平翘舌 zh ch sh ↔ z c s"
RIME_I18N[zh:fz_n_l]="鼻音/边音 n ↔ l"
RIME_I18N[zh:fz_f_h]="f ↔ h"
RIME_I18N[zh:fz_l_r]="l ↔ r"
RIME_I18N[zh:fz_g_k]="g ↔ k"
RIME_I18N[zh:fz_in_ing]="前后鼻音 in ↔ ing"
RIME_I18N[zh:fz_en_eng]="前后鼻音 en ↔ eng"
RIME_I18N[zh:fz_an_ang]="前后鼻音 an ↔ ang"
RIME_I18N[zh:fz_ian_iang]="ian ↔ iang"
RIME_I18N[zh:fz_uan_uang]="uan ↔ uang"
RIME_I18N[ja:fz_zh_z]="そり舌 zh ch sh ↔ z c s"
RIME_I18N[ja:fz_n_l]="n ↔ l"
RIME_I18N[ja:fz_f_h]="f ↔ h"
RIME_I18N[ja:fz_l_r]="l ↔ r"
RIME_I18N[ja:fz_g_k]="g ↔ k"
RIME_I18N[ja:fz_in_ing]="in ↔ ing(前鼻/後鼻)"
RIME_I18N[ja:fz_en_eng]="en ↔ eng(前鼻/後鼻)"
RIME_I18N[ja:fz_an_ang]="an ↔ ang(前鼻/後鼻)"
RIME_I18N[ja:fz_ian_iang]="ian ↔ iang"
RIME_I18N[ja:fz_uan_uang]="uan ↔ uang"

# ui() chrome (ubuntu-setup): headers, notes, row labels, prompts, confirms, run titles.
RIME_I18N[en:ui_ssh_note]="Desktop input method — over SSH/headless these apply where the desktop runs, after re-login."
RIME_I18N[en:ui_sec_engine]="Engine"
RIME_I18N[en:ui_im_environment]="IM environment"
RIME_I18N[en:ui_state_on]="on"
RIME_I18N[en:ui_state_missing]="missing"
RIME_I18N[en:ui_fcitx5_autostart]="fcitx5 autostart"
RIME_I18N[en:ui_rime_engine]="RIME engine"
RIME_I18N[en:ui_sec_schemas]="Schemas"
RIME_I18N[en:ui_ice_owns_schemas]="雾凇拼音 (rime-ice) is active and owns the schema list — remove it to manage schemas here."
RIME_I18N[en:ui_add_schema_row]="add another schema by id…"
RIME_I18N[en:ui_sec_options]="Options"
RIME_I18N[en:ui_candidates_per_page]="Candidates per page"
RIME_I18N[en:ui_ice_remove_row]="installed — remove rime-ice"
RIME_I18N[en:ui_ice_install_row]="install rime-ice (batteries-included config)"
RIME_I18N[en:ui_sec_actions]="Actions"
RIME_I18N[en:ui_deploy_now]="Deploy now (apply config)"
RIME_I18N[en:ui_apply_recommended]="Apply recommended setup"
RIME_I18N[en:ui_footer_hints]="↑↓ move   space toggle   d default   a add   ↵ edit/run   esc/q close"
RIME_I18N[en:ui_run_disable_schema]="disable schema"
RIME_I18N[en:ui_run_enable_schema]="enable schema"
RIME_I18N[en:ui_run_set_default_schema]="set default schema"
RIME_I18N[en:ui_run_add_schema]="add schema"
RIME_I18N[en:ui_prompt_schema_id]="schema id to enable (e.g. bopomofo, wubi86)"
RIME_I18N[en:ui_confirm_remove_engine]="Uninstall the RIME engine? (fcitx5 and your data are kept)"
RIME_I18N[en:ui_prompt_page_size]="candidates per page (5-10)"
RIME_I18N[en:ui_run_set_page_size]="set page size"
RIME_I18N[en:ui_confirm_install_ice]="Install 雾凇拼音 (rime-ice)? Clones a config repo from GitHub."
RIME_I18N[en:ui_run_install_ice]="install rime-ice"
RIME_I18N[en:ui_confirm_remove_ice]="Remove rime-ice and restore the built-in schemas?"
RIME_I18N[en:ui_run_remove_ice]="remove rime-ice"
RIME_I18N[en:ui_run_deploy]="deploy"
RIME_I18N[en:ui_run_apply_recommended]="apply recommended"
RIME_I18N[en:ui_sec_fuzzy]="Fuzzy pinyin (模糊音)"
RIME_I18N[en:ui_fuzzy_note]="Tolerate easily-confused initials/finals. Applies to the active pinyin schema; more pairs = more candidates."
RIME_I18N[en:ui_fuzzy_no_target]="No pinyin schema is active — enable one (or 雾凇拼音) for fuzzy pinyin to take effect."
RIME_I18N[en:ui_run_enable_fuzzy]="enable fuzzy"
RIME_I18N[en:ui_run_disable_fuzzy]="disable fuzzy"
RIME_I18N[en:ui_state_off]="off"
RIME_I18N[en:ui_silence_diagnose]="Silence GNOME-Wayland diagnose popup"
RIME_I18N[en:ui_diagnose_note]="fcitx5 nags every GNOME-Wayland login to install the kimpanel extension — RIME works without it; this hides that popup."
RIME_I18N[en:ui_run_silence]="toggle wayland diagnose"
RIME_I18N[zh:ui_ssh_note]="桌面输入法 —— 经 SSH/无头时这些设置在运行桌面的机器上生效,需重新登录。"
RIME_I18N[zh:ui_sec_engine]="引擎"
RIME_I18N[zh:ui_im_environment]="输入法环境"
RIME_I18N[zh:ui_state_on]="已启用"
RIME_I18N[zh:ui_state_missing]="缺失"
RIME_I18N[zh:ui_fcitx5_autostart]="fcitx5 自启动"
RIME_I18N[zh:ui_rime_engine]="RIME 引擎"
RIME_I18N[zh:ui_sec_schemas]="输入方案"
RIME_I18N[zh:ui_ice_owns_schemas]="雾凇拼音 (rime-ice) 已启用并接管方案列表 —— 移除它才能在此管理方案。"
RIME_I18N[zh:ui_add_schema_row]="按 id 添加其他方案…"
RIME_I18N[zh:ui_sec_options]="选项"
RIME_I18N[zh:ui_candidates_per_page]="每页候选词数"
RIME_I18N[zh:ui_ice_remove_row]="已安装 —— 移除 rime-ice"
RIME_I18N[zh:ui_ice_install_row]="安装 rime-ice(开箱即用配置)"
RIME_I18N[zh:ui_sec_actions]="操作"
RIME_I18N[zh:ui_deploy_now]="立即部署(应用配置)"
RIME_I18N[zh:ui_apply_recommended]="应用推荐设置"
RIME_I18N[zh:ui_footer_hints]="↑↓ 移动   space 切换   d 设默认   a 添加   ↵ 编辑/运行   esc/q 关闭"
RIME_I18N[zh:ui_run_disable_schema]="禁用方案"
RIME_I18N[zh:ui_run_enable_schema]="启用方案"
RIME_I18N[zh:ui_run_set_default_schema]="设默认方案"
RIME_I18N[zh:ui_run_add_schema]="添加方案"
RIME_I18N[zh:ui_prompt_schema_id]="要启用的方案 id(如 bopomofo、wubi86)"
RIME_I18N[zh:ui_confirm_remove_engine]="卸载 RIME 引擎?(保留 fcitx5 与你的数据)"
RIME_I18N[zh:ui_prompt_page_size]="每页候选词数(5-10)"
RIME_I18N[zh:ui_run_set_page_size]="设置每页候选数"
RIME_I18N[zh:ui_confirm_install_ice]="安装 雾凇拼音 (rime-ice)?将从 GitHub 克隆一个配置仓库。"
RIME_I18N[zh:ui_run_install_ice]="安装 rime-ice"
RIME_I18N[zh:ui_confirm_remove_ice]="移除 rime-ice 并恢复内置方案?"
RIME_I18N[zh:ui_run_remove_ice]="移除 rime-ice"
RIME_I18N[zh:ui_run_deploy]="部署"
RIME_I18N[zh:ui_run_apply_recommended]="应用推荐"
RIME_I18N[zh:ui_sec_fuzzy]="模糊音"
RIME_I18N[zh:ui_fuzzy_note]="容错易混的声母/韵母。作用于当前拼音方案;开得越多候选越杂。"
RIME_I18N[zh:ui_fuzzy_no_target]="当前没有启用拼音方案 —— 启用一个(或雾凇拼音)模糊音才会生效。"
RIME_I18N[zh:ui_run_enable_fuzzy]="启用模糊音"
RIME_I18N[zh:ui_run_disable_fuzzy]="禁用模糊音"
RIME_I18N[zh:ui_state_off]="已关闭"
RIME_I18N[zh:ui_silence_diagnose]="静默 GNOME-Wayland 自检弹窗"
RIME_I18N[zh:ui_diagnose_note]="GNOME-Wayland 每次登录 fcitx5 都提示装 kimpanel 扩展 —— 没它 RIME 也能用,此项隐藏该弹窗。"
RIME_I18N[zh:ui_run_silence]="切换 wayland 自检提示"
RIME_I18N[ja:ui_ssh_note]="デスクトップ入力メソッド — SSH/ヘッドレスではデスクトップが動くマシンで再ログイン後に有効になります。"
RIME_I18N[ja:ui_sec_engine]="エンジン"
RIME_I18N[ja:ui_im_environment]="IM 環境"
RIME_I18N[ja:ui_state_on]="有効"
RIME_I18N[ja:ui_state_missing]="なし"
RIME_I18N[ja:ui_fcitx5_autostart]="fcitx5 自動起動"
RIME_I18N[ja:ui_rime_engine]="RIME エンジン"
RIME_I18N[ja:ui_sec_schemas]="入力スキーマ(输入方案)"
RIME_I18N[ja:ui_ice_owns_schemas]="雾凇拼音 (rime-ice) が有効でスキーマ一覧を管理しています — ここで管理するには先に削除してください。"
RIME_I18N[ja:ui_add_schema_row]="id でほかのスキーマを追加…"
RIME_I18N[ja:ui_sec_options]="オプション"
RIME_I18N[ja:ui_candidates_per_page]="1 ページの候補数"
RIME_I18N[ja:ui_ice_remove_row]="インストール済み — rime-ice を削除"
RIME_I18N[ja:ui_ice_install_row]="rime-ice をインストール(設定込み)"
RIME_I18N[ja:ui_sec_actions]="操作"
RIME_I18N[ja:ui_deploy_now]="今すぐデプロイ(設定を適用)"
RIME_I18N[ja:ui_apply_recommended]="推奨設定を適用"
RIME_I18N[ja:ui_footer_hints]="↑↓ 移動   space 切替   d 既定   a 追加   ↵ 編集/実行   esc/q 閉じる"
RIME_I18N[ja:ui_run_disable_schema]="スキーマを無効化"
RIME_I18N[ja:ui_run_enable_schema]="スキーマを有効化"
RIME_I18N[ja:ui_run_set_default_schema]="既定スキーマを設定"
RIME_I18N[ja:ui_run_add_schema]="スキーマを追加"
RIME_I18N[ja:ui_prompt_schema_id]="有効化するスキーマ id(例: bopomofo、wubi86)"
RIME_I18N[ja:ui_confirm_remove_engine]="RIME エンジンをアンインストールしますか?(fcitx5 とデータは保持されます)"
RIME_I18N[ja:ui_prompt_page_size]="1 ページの候補数(5-10)"
RIME_I18N[ja:ui_run_set_page_size]="ページ候補数を設定"
RIME_I18N[ja:ui_confirm_install_ice]="雾凇拼音 (rime-ice) をインストールしますか?GitHub から設定リポジトリを clone します。"
RIME_I18N[ja:ui_run_install_ice]="rime-ice をインストール"
RIME_I18N[ja:ui_confirm_remove_ice]="rime-ice を削除して内蔵スキーマを復元しますか?"
RIME_I18N[ja:ui_run_remove_ice]="rime-ice を削除"
RIME_I18N[ja:ui_run_deploy]="デプロイ"
RIME_I18N[ja:ui_run_apply_recommended]="推奨を適用"
RIME_I18N[ja:ui_sec_fuzzy]="あいまい音(模糊音)"
RIME_I18N[ja:ui_fuzzy_note]="紛らわしい声母/韵母を許容。有効な拼音スキーマに適用、増やすほど候補が増えます。"
RIME_I18N[ja:ui_fuzzy_no_target]="拼音スキーマが無効です —— いずれか(または雾凇拼音)を有効にすると効きます。"
RIME_I18N[ja:ui_run_enable_fuzzy]="あいまい音を有効化"
RIME_I18N[ja:ui_run_disable_fuzzy]="あいまい音を無効化"
RIME_I18N[ja:ui_state_off]="無効"
RIME_I18N[ja:ui_silence_diagnose]="GNOME-Wayland 自己診断ポップアップを抑制"
RIME_I18N[ja:ui_diagnose_note]="GNOME-Wayland ではログインごとに kimpanel 拡張を勧められます —— なくても RIME は動作。これで非表示にします。"
RIME_I18N[ja:ui_run_silence]="wayland 自己診断を切替"

# Gloss for a schema id, in the active UI language (English fallback, then the id itself).
_rime_schema_desc() {
  local lang="${UI_LANG:-en}" key="$1"
  case "$lang" in en|zh|ja) ;; *) lang="en" ;; esac
  printf '%s' "${RIME_I18N[$lang:$key]:-${RIME_I18N[en:$key]:-$key}}"
}

# Gloss for a fuzzy pair key (looks up the fz_<key> entry), in the active UI language.
_rime_fuzzy_desc() {
  local lang="${UI_LANG:-en}" key="fz_$1"
  case "$lang" in en|zh|ja) ;; *) lang="en" ;; esac
  printf '%s' "${RIME_I18N[$lang:$key]:-${RIME_I18N[en:$key]:-$1}}"
}

# _rime_t KEY — localized UI-chrome string for $UI_LANG (en/zh/ja), fallback en -> key.
_rime_t() {
  local lang="${UI_LANG:-en}" key="$1"
  case "$lang" in en|zh|ja) ;; *) lang="en" ;; esac
  printf '%s' "${RIME_I18N[$lang:$key]:-${RIME_I18N[en:$key]:-$key}}"
}

meta() {
  cat <<'META'
key=rime
name=RIME
category=common
ops=install,remove,configure,deploy,install-rime-ice,remove-rime-ice
desc=RIME input method on fcitx5 — installs the engine + frontends, manages schemas (输入方案), optional 雾凇拼音(rime-ice); desktop-only (honest no-op note over SSH)
META
}

# --- Install probe -------------------------------------------------------------

# Exit 0 iff the RIME engine for fcitx5 is installed (the thing this script is about).
status() {
  pkg_installed fcitx5-rime || return 1
  local v; v="$(fcitx5 --version 2>/dev/null | head -n1 || true)"
  printf 'fcitx5-rime installed%s\n' "${v:+ (${v})}"
  return 0
}

# --- Home / paths / preferences ------------------------------------------------

# Resolve the user's home (refusing a sudo-wrapped run — RIME config must stay user-owned),
# then derive every path we touch. Mirrors scripts/ghostty.sh's _ghostty_resolve_home.
_rime_resolve_home() {
  if [[ $EUID -eq 0 && -n "${SUDO_USER:-}" ]]; then
    log_err "Run RIME as your normal user, not via sudo — its config lives in your home"
    log_err "(~/.config, ~/.local/share) and must stay user-owned (apt steps escalate"
    log_err "per-command on their own)."
    return 1
  fi
  local user; user="${SUDO_USER:-$(id -un)}"
  _R_HOME="${HOME:-}"
  [[ -n "$_R_HOME" ]] || _R_HOME="$(getent passwd "$user" | cut -d: -f6 || true)"
  [[ -n "$_R_HOME" ]] || { log_err "Could not resolve the home directory for '$user'."; return 1; }
  local xdg_cfg="${XDG_CONFIG_HOME:-$_R_HOME/.config}"
  local xdg_data="${XDG_DATA_HOME:-$_R_HOME/.local/share}"
  _R_RIME_DIR="$xdg_data/fcitx5/rime"                         # fcitx5's RIME user dir
  _R_ENVD="$xdg_cfg/environment.d/ubuntu-setup-rime.conf"     # managed IM environment
  _R_AUTOSTART="$xdg_cfg/autostart/org.fcitx.Fcitx5.desktop"  # managed fcitx5 login autostart
  _R_PREF_DIR="$xdg_cfg/ubuntu-setup"
  _R_PREF="$_R_PREF_DIR/rime.conf"                            # the kit's KEY=VALUE store
  _R_ICE_CLONE="$xdg_data/ubuntu-setup/rime-ice"             # kit-owned rime-ice clone
  _R_ICE_MANIFEST="$_R_PREF_DIR/rime-ice.manifest"           # paths rime-ice put in _R_RIME_DIR
  _R_XINPUTRC="$_R_HOME/.xinputrc"                            # im-config's framework selection
  _R_FCITX5_NOTIF="$xdg_cfg/fcitx5/conf/notifications.conf"   # fcitx5's OWN notifications config
}

_rime_defaults() {
  FRAMEWORK=fcitx5
  SCHEMAS="luna_pinyin_simp luna_pinyin"
  PAGE_SIZE=5
  RIME_ICE=0
  FUZZY=""           # space-separated set of enabled fuzzy-pair keys (see _RIME_FUZZY); off by default
  SILENCE_WAYLAND_DIAGNOSE=0   # hide fcitx5's GNOME-Wayland diagnose popup; off (conservative) by default
}

_rime_pagesize_valid() { [[ "$1" =~ ^[0-9]+$ ]] && (( $1 >= 5 && $1 <= 10 )); }
_rime_schema_id_valid() { [[ "$1" =~ ^[A-Za-z0-9_]+$ ]]; }
_rime_fuzzy_valid() { local k; for k in "${_RIME_FUZZY[@]}"; do [[ "$k" == "$1" ]] && return 0; done; return 1; }

_rime_load() {
  _rime_defaults
  [[ -f "${_R_PREF:-}" ]] || return 0
  local line key val
  while IFS= read -r line || [[ -n "$line" ]]; do
    case "$line" in ''|\#*) continue ;; esac
    key="${line%%=*}"; val="${line#*=}"
    case "$key" in
      FRAMEWORK) [[ "$val" == fcitx5 ]] && FRAMEWORK="$val" ;;
      SCHEMAS)   SCHEMAS="$val" ;;
      PAGE_SIZE) _rime_pagesize_valid "$val" && PAGE_SIZE="$val" ;;
      RIME_ICE)  [[ "$val" == 0 || "$val" == 1 ]] && RIME_ICE="$val" ;;
      FUZZY)     FUZZY="$val" ;;
      SILENCE_WAYLAND_DIAGNOSE) [[ "$val" == 0 || "$val" == 1 ]] && SILENCE_WAYLAND_DIAGNOSE="$val" ;;
    esac
  done <"$_R_PREF"
  [[ -n "${SCHEMAS// /}" ]] || SCHEMAS="luna_pinyin_simp luna_pinyin"
  # Drop any unknown fuzzy keys that crept into the conf (keep curated order-agnostic membership).
  local fk fclean=""
  for fk in $FUZZY; do _rime_fuzzy_valid "$fk" && fclean="${fclean:+$fclean }$fk"; done
  FUZZY="$fclean"
}

_rime_save() {
  mkdir -p "$_R_PREF_DIR"
  local tmp; tmp="$(mktemp)"
  {
    printf 'FRAMEWORK=%s\n' "$FRAMEWORK"
    printf 'SCHEMAS=%s\n'   "$SCHEMAS"
    printf 'PAGE_SIZE=%s\n' "$PAGE_SIZE"
    printf 'RIME_ICE=%s\n'  "$RIME_ICE"
    printf 'FUZZY=%s\n'     "$FUZZY"
    printf 'SILENCE_WAYLAND_DIAGNOSE=%s\n' "$SILENCE_WAYLAND_DIAGNOSE"
  } >"$tmp"
  if [[ -f "$_R_PREF" ]] && cmp -s "$tmp" "$_R_PREF"; then rm -f "$tmp"; return 0; fi
  backup_file "$_R_PREF"
  mv "$tmp" "$_R_PREF" || { rm -f "$tmp"; return 1; }
}

# --- Schema-list helpers (operate on the space-separated SCHEMAS string) --------

_rime_schema_in() { local s; for s in $SCHEMAS; do [[ "$s" == "$1" ]] && return 0; done; return 1; }
_rime_schema_add() { _rime_schema_in "$1" || SCHEMAS="${SCHEMAS:+$SCHEMAS }$1"; }
_rime_schema_remove() {
  local s out=""
  for s in $SCHEMAS; do [[ "$s" == "$1" ]] || out="${out:+$out }$s"; done
  SCHEMAS="$out"
}
_rime_schema_set_default() { _rime_schema_remove "$1"; SCHEMAS="$1${SCHEMAS:+ $SCHEMAS}"; }
_rime_default_schema() { printf '%s' "${SCHEMAS%% *}"; }

# --- Fuzzy-set helpers (operate on the space-separated FUZZY string) -------------

_rime_fuzzy_in() { local s; for s in $FUZZY; do [[ "$s" == "$1" ]] && return 0; done; return 1; }
_rime_fuzzy_add() { _rime_fuzzy_in "$1" || FUZZY="${FUZZY:+$FUZZY }$1"; }
_rime_fuzzy_remove() {
  local s out=""
  for s in $FUZZY; do [[ "$s" == "$1" ]] || out="${out:+$out }$s"; done
  FUZZY="$out"
}

# Echo (one per line) the schema ids that should receive the fuzzy patch right now: rime_ice when
# 雾凇拼音 owns the schema list, otherwise the enabled full-pinyin schemas. Used to decide where to
# write — and, by elimination from _RIME_FUZZY_SCHEMAS, where to clean up stale fuzzy files.
_rime_fuzzy_targets() {
  if [[ "${RIME_ICE:-0}" == 1 ]]; then printf '%s\n' rime_ice; return 0; fi
  local s
  for s in $SCHEMAS; do
    case " ${_RIME_FUZZY_SCHEMAS[*]} " in *" $s "*) printf '%s\n' "$s" ;; esac
  done
}

# --- Small environment probes --------------------------------------------------

# True when there is no local graphical session to deploy into (SSH or no display).
_rime_no_display() {
  [[ -n "${SSH_CONNECTION:-}${SSH_TTY:-}${SSH_CLIENT:-}" ]] && return 0
  [[ -z "${WAYLAND_DISPLAY:-}${DISPLAY:-}" ]]
}

# A short, honest note about where these settings take effect.
_rime_where_note() {
  if [[ -n "${SSH_CONNECTION:-}${SSH_TTY:-}${SSH_CLIENT:-}" ]]; then
    log_warn "This is an SSH session. RIME/fcitx5 is a desktop input method — these settings"
    log_warn "apply on a machine with a graphical session, not to this remote shell."
  fi
}

# Desktop / session-type probes (best-effort; vars may be unset in a non-graphical shell).
_rime_is_gnome()   { case "${XDG_CURRENT_DESKTOP:-}" in *[Gg][Nn][Oo][Mm][Ee]*) return 0 ;; *) return 1 ;; esac; }
_rime_is_wayland() { [[ "${XDG_SESSION_TYPE:-}" == wayland || -n "${WAYLAND_DISPLAY:-}" ]]; }

# GNOME-on-Wayland caveat: GNOME runs its own IBus and Mutter routes native-Wayland apps
# through it (it does not implement the Wayland input-method protocol fcitx5 uses). fcitx5
# still serves X11/XWayland apps via GTK_IM_MODULE/XMODIFIERS. Tell the truth + give outs.
_rime_wayland_note() {
  _rime_is_gnome && _rime_is_wayland || return 0
  log_warn "You're on GNOME (Wayland). GNOME starts its own IBus and handles native-Wayland"
  log_warn "apps itself, so fcitx5/RIME covers X11/XWayland apps (most apps) but GNOME may keep"
  log_warn "intercepting some native-Wayland ones. For the most reliable fcitx5 experience:"
  log_warn "  • choose \"Ubuntu on Xorg\" at the login screen (gear icon, bottom-right), or"
  log_warn "  • drop GNOME's competing Chinese input source so it can't shadow fcitx5:"
  log_warn "      gsettings set org.gnome.desktop.input-sources sources \"[('xkb','us')]\""
}

# Notes printed after install / config changes (re-login reminder + honesty).
_rime_post_install_notes() {
  log_info "fcitx5 is set to autostart at login. Log out and back in so it starts and the"
  log_info "input-method environment applies; then switch with Ctrl+Space (fcitx5's toggle)."
  _rime_where_note
  _rime_wayland_note
}

# Is `pkg` an installable apt candidate right now? (No sudo; reads existing apt lists.)
# LC_ALL=C forces apt-cache's field labels to English — without it, on a localized system
# the label is translated (e.g. zh "候选：") and grepping for "Candidate:" matches nothing,
# so every probe falsely reports "unavailable". (Same rule as the lib's locale-proofing:
# decide on stable text, never on text that gets translated.)
_rime_apt_available() {
  local cand; cand="$(LC_ALL=C apt-cache policy "$1" 2>/dev/null | awk '/Candidate:/{print $2; exit}')"
  [[ -n "$cand" && "$cand" != "(none)" ]]
}

# Install the GTK/Qt IM modules so apps use fcitx5's native frontend. WITHOUT these, GTK/Qt
# apps fall back to XIM (XMODIFIERS), which works for typing but mis-positions the candidate
# window (it floats to a screen corner instead of following the cursor). Prefer the metapackage
# fcitx5-frontend-all (covers gtk2/3/4 + qt5/6, future-proof); fall back to the modern set if
# the metapackage is absent. recommends are off by lib policy, so we install these explicitly.
_rime_install_frontends() {
  if _rime_apt_available fcitx5-frontend-all; then
    apt_install fcitx5-frontend-all || log_warn "Could not install fcitx5-frontend-all (GTK/Qt IM modules)."
    return 0
  fi
  local p any=0
  for p in fcitx5-frontend-gtk3 fcitx5-frontend-gtk4 fcitx5-frontend-qt5 fcitx5-frontend-qt6; do
    if _rime_apt_available "$p"; then
      if apt_install "$p"; then any=1; else log_warn "Could not install $p."; fi
    fi
  done
  (( any )) || log_warn "No fcitx5 GTK/Qt IM modules were available — apps may fall back to XIM (mis-positioned candidate window)."
}

# Are the GTK/Qt IM modules present? (Used to self-heal older installs that missed them.)
_rime_frontends_present() {
  pkg_installed fcitx5-frontend-gtk3 || pkg_installed fcitx5-frontend-gtk4 \
    || pkg_installed fcitx5-frontend-qt6 || pkg_installed fcitx5-frontend-all
}

# --- Managed files (own them; rewrite wholesale + convergent; back up first) ----

# The fcitx5 input-method environment (read by systemd/GNOME/KDE graphical sessions).
_rime_write_envd() {
  mkdir -p "$(dirname "$_R_ENVD")"
  local tmp; tmp="$(mktemp)"
  {
    printf '# Generated by ubuntu-setup (swkit rime). Do not edit; re-run: swkit rime install\n'
    printf 'GTK_IM_MODULE=fcitx\n'
    printf 'QT_IM_MODULE=fcitx\n'
    printf 'XMODIFIERS=@im=fcitx\n'
  } >"$tmp"
  if [[ -f "$_R_ENVD" ]] && cmp -s "$tmp" "$_R_ENVD"; then rm -f "$tmp"; return 0; fi
  backup_file "$_R_ENVD"
  mv "$tmp" "$_R_ENVD" || { rm -f "$tmp"; return 1; }
}

# A managed XDG autostart entry that launches fcitx5 at login. This is REQUIRED on Wayland
# (Ubuntu's default session): im-config/im-launch only starts the IM daemon for X11 sessions
# (its Wayland branch is disabled), and the fcitx5 package ships no /etc/xdg/autostart entry,
# so without this nothing starts fcitx5 and the desktop falls back to its built-in IBus.
# GNOME/KDE process ~/.config/autostart on login for both X11 and Wayland.
_rime_write_autostart() {
  mkdir -p "$(dirname "$_R_AUTOSTART")"
  local exe; exe="$(command -v fcitx5 2>/dev/null || echo /usr/bin/fcitx5)"
  local tmp; tmp="$(mktemp)"
  {
    printf '[Desktop Entry]\n'
    printf '# Generated by ubuntu-setup (swkit rime). Autostarts fcitx5 at login — needed on\n'
    printf '# Wayland/GNOME, where im-config/im-launch does NOT start the IM daemon. Delete to disable.\n'
    printf 'Type=Application\n'
    printf 'Name=Fcitx 5 (ubuntu-setup)\n'
    printf 'Exec=%s\n' "$exe"
    printf 'Icon=fcitx\n'
    printf 'Terminal=false\n'
    printf 'StartupNotify=false\n'
    printf 'X-GNOME-Autostart-enabled=true\n'
  } >"$tmp"
  if [[ -f "$_R_AUTOSTART" ]] && cmp -s "$tmp" "$_R_AUTOSTART"; then rm -f "$tmp"; return 0; fi
  backup_file "$_R_AUTOSTART"
  mv "$tmp" "$_R_AUTOSTART" || { rm -f "$tmp"; return 1; }
}

# The managed RIME patch. We own default.custom.yaml; RIME merges *.custom.yaml as patches
# over its built-in defaults, and default.custom.yaml is exactly that user-patch entry point.
# When rime-ice is active we DON'T set schema_list (rime-ice's own default.yaml owns it).
_rime_write_default_yaml() {
  mkdir -p "$_R_RIME_DIR"
  local f="$_R_RIME_DIR/default.custom.yaml" tmp; tmp="$(mktemp)"
  {
    printf '# Generated by ubuntu-setup (swkit rime). Do not edit; re-run: swkit rime configure\n'
    printf 'patch:\n'
    if [[ "${RIME_ICE:-0}" != 1 ]]; then
      printf '  schema_list:\n'
      local s
      for s in $SCHEMAS; do printf '    - schema: %s\n' "$s"; done
    fi
    printf '  "menu/page_size": %s\n' "$PAGE_SIZE"
  } >"$tmp"
  if [[ -f "$f" ]] && cmp -s "$tmp" "$f"; then rm -f "$tmp"; return 0; fi
  backup_file "$f"
  mv "$tmp" "$f" || { rm -f "$tmp"; return 1; }
}

# True iff <file> exists and its first line carries our marker (i.e. WE generated it). Lets us
# overwrite/remove our own fuzzy files while never clobbering a user's hand-written <schema>.custom.yaml.
_rime_file_is_ours() { local first; [[ -f "$1" ]] && IFS= read -r first <"$1" && [[ "$first" == "$_RIME_FUZZY_MARK"* ]]; }

# Write the managed fuzzy patch for one schema id (appends the enabled pairs' derive rules to that
# schema's speller/algebra via 'speller/algebra/+', so we never reproduce its full algebra). Pairs
# are emitted in curated (_RIME_FUZZY) order for a stable, convergent file.
_rime_write_one_fuzzy() {
  local id="$1" tmp
  local f="$_R_RIME_DIR/$id.custom.yaml"
  tmp="$(mktemp)"
  {
    printf '%s. Do not edit; re-run: swkit rime configure\n' "$_RIME_FUZZY_MARK"
    printf '# Fuzzy pinyin (模糊音) for schema: %s — appended to its speller/algebra.\n' "$id"
    printf 'patch:\n'
    printf "  'speller/algebra/+':\n"
    local k rule
    for k in "${_RIME_FUZZY[@]}"; do
      _rime_fuzzy_in "$k" || continue
      while IFS= read -r rule; do printf '    - %s\n' "$rule"; done < <(_rime_fuzzy_rules "$k")
    done
  } >"$tmp"
  if [[ -f "$f" ]] && cmp -s "$tmp" "$f"; then rm -f "$tmp"; return 0; fi
  # Back up (and warn about) a pre-existing NON-managed file before we take it over.
  if [[ -f "$f" ]] && ! _rime_file_is_ours "$f"; then
    backup_file "$f"
    log_warn "Took over an existing $id.custom.yaml (backed up) to manage fuzzy pinyin."
  fi
  mv "$tmp" "$f" || { rm -f "$tmp"; return 1; }
}

# Converge every fuzzy-capable schema's per-schema file: write it when the schema is an active
# target AND fuzzy is enabled, otherwise remove OUR file (leave a user's own untouched). Iterating
# the full fixed set means stale files are cleaned up when schemas change or rime-ice toggles.
_rime_write_fuzzy_all() {
  local targets; targets=" $(_rime_fuzzy_targets | tr '\n' ' ') "
  local id f
  for id in "${_RIME_FUZZY_SCHEMAS[@]}"; do
    f="$_R_RIME_DIR/$id.custom.yaml"
    if [[ -n "${FUZZY// /}" && "$targets" == *" $id "* ]]; then
      _rime_write_one_fuzzy "$id"
    elif _rime_file_is_ours "$f"; then
      rm -f "$f"
    fi
  done
}

# Render all managed RIME patch files (global default + per-schema fuzzy) from the loaded prefs.
_rime_render() { _rime_write_default_yaml; _rime_write_fuzzy_all; }

# Warn (best-effort) when fuzzy is enabled but nothing will receive it — e.g. only wubi/cangjie
# schemas are active. The patch is still saved; it just won't take effect until a pinyin schema is on.
_rime_warn_no_fuzzy_target() {
  [[ -n "${FUZZY// /}" ]] || return 0
  [[ -z "$(_rime_fuzzy_targets)" ]] || return 0
  log_warn "Fuzzy pinyin is set but no pinyin schema is active — enable one (or 雾凇拼音) for it to take effect."
}

# --- fcitx5 GNOME-Wayland diagnose popup (silence on demand) -------------------
# notifications.conf is fcitx5's OWN file (it rewrites it when you click "Do not show again"), so
# unlike our managed files we do NOT regenerate it wholesale: we surgically read the existing
# [HiddenNotifications] tip ids and add/remove only ours, preserving the rest. fcitx5 serializes
# this std::vector as a [HiddenNotifications] section with numbered keys (0=…, 1=…); empty is the
# bare top-level line `HiddenNotifications=`.

# Echo the hidden-notification tip ids currently listed in notifications.conf, one per line.
_rime_read_hidden_notifs() {
  [[ -f "$_R_FCITX5_NOTIF" ]] || return 0
  local line in_section=0
  while IFS= read -r line || [[ -n "$line" ]]; do
    case "$line" in
      '[HiddenNotifications]') in_section=1; continue ;;
      '['*']')                 in_section=0; continue ;;
    esac
    (( in_section )) || continue
    case "$line" in [0-9]*=*) printf '%s\n' "${line#*=}" ;; esac
  done <"$_R_FCITX5_NOTIF"
}

# Converge notifications.conf so our GNOME-Wayland diagnose tip is hidden (SILENCE_WAYLAND_DIAGNOSE=1)
# or shown (=0), preserving every other hidden-tip id. Semantic no-op when already in the wanted state
# (never rewrites fcitx5's file needlessly, so a default install never touches it); backs up first.
_rime_apply_diagnose_silence() {
  local tip="$_RIME_WAYLAND_DIAGNOSE_TIP" want="${SILENCE_WAYLAND_DIAGNOSE:-0}"
  local -a others=(); local id have_ours=0
  while IFS= read -r id; do
    [[ -n "$id" ]] || continue
    if [[ "$id" == "$tip" ]]; then have_ours=1; else others+=("$id"); fi
  done < <(_rime_read_hidden_notifs)
  # Already in the wanted state? (want==1 && present, or want==0 && absent) → nothing to write.
  [[ "$want" == "$have_ours" ]] && return 0
  local -a ids=("${others[@]}")
  [[ "$want" == 1 ]] && ids+=("$tip")
  mkdir -p "$(dirname "$_R_FCITX5_NOTIF")"
  backup_file "$_R_FCITX5_NOTIF"
  local tmp first; tmp="$(mktemp)"
  {
    # Preserve fcitx5's own (locale-dependent) leading comment if present, else write a stable one.
    if [[ -f "$_R_FCITX5_NOTIF" ]] && IFS= read -r first <"$_R_FCITX5_NOTIF" && [[ "$first" == '#'* ]]; then
      printf '%s\n' "$first"
    else
      printf '# Hidden Notifications (the wayland-diagnose tip is managed by ubuntu-setup: swkit rime)\n'
    fi
    if (( ${#ids[@]} == 0 )); then
      printf 'HiddenNotifications=\n'
    else
      printf '[HiddenNotifications]\n'
      local i=0
      for id in "${ids[@]}"; do printf '%s=%s\n' "$i" "$id"; i=$((i+1)); done
    fi
  } >"$tmp"
  mv "$tmp" "$_R_FCITX5_NOTIF" || { rm -f "$tmp"; return 1; }
}

# --- Deploy (apply RIME config) ------------------------------------------------

_rime_deploy() {
  if _rime_no_display; then
    log_info "No local graphical session — deploy where the desktop runs (fcitx5 tray ▸"
    log_info "Restart / Deploy), or it applies on next login."
    _rime_where_note
    return 0
  fi
  if have_cmd fcitx5-remote && fcitx5-remote -r 2>/dev/null; then
    log_info "Asked the running fcitx5 to reload (redeploys RIME)."
  else
    log_info "Could not reach a running fcitx5 — deploy via the tray (▸ Deploy) or re-login."
  fi
}

do_deploy() { _rime_resolve_home || return 1; _rime_deploy; }

# --- Install / remove ----------------------------------------------------------

do_install() {
  _rime_resolve_home || return 1
  if status >/dev/null 2>&1; then
    log_info "RIME engine already installed ($(status 2>/dev/null)) — converging config."
    _rime_load
    # Self-heal older installs that missed the GTK/Qt IM modules (their absence makes apps
    # fall back to XIM, which mis-positions the candidate window).
    if ! _rime_frontends_present; then
      log_info "GTK/Qt IM modules are missing — installing them (apps were falling back to XIM)…"
      _rime_install_frontends
    fi
    _rime_write_envd || log_warn "Could not write the IM environment file."
    _rime_write_autostart || log_warn "Could not write the fcitx5 autostart entry."
    # Re-assert the framework selection too (harmless if already fcitx5).
    have_cmd im-config && { im-config -n fcitx5 >/dev/null 2>&1 || true; }
    [[ -f "$_R_RIME_DIR/default.custom.yaml" ]] || _rime_write_default_yaml
    _rime_write_fuzzy_all   # converge per-schema fuzzy files (no-op when FUZZY is empty)
    _rime_apply_diagnose_silence || log_warn "Could not update fcitx5's notification settings."
    log_info "Configure schemas with:  swkit rime configure   (or open: swkit rime)"
    _rime_post_install_notes
    return 0
  fi

  # Core: framework + RIME engine + GUI config tool + the framework selector.
  apt_install fcitx5 fcitx5-rime fcitx5-config-qt im-config

  # GTK/Qt IM modules (without them apps fall back to XIM → mis-positioned candidate window).
  _rime_install_frontends

  # Select fcitx5 as the input-method framework (Ubuntu's blessed selector; user-space).
  if have_cmd im-config; then
    im-config -n fcitx5 >/dev/null 2>&1 || log_warn "im-config -n fcitx5 did not complete — set the framework manually if needed."
  fi

  _rime_load
  _rime_write_envd || log_warn "Could not write the IM environment file."
  _rime_write_autostart || log_warn "Could not write the fcitx5 autostart entry."
  [[ -f "$_R_RIME_DIR/default.custom.yaml" ]] || _rime_write_default_yaml
  _rime_write_fuzzy_all   # converge per-schema fuzzy files (no-op when FUZZY is empty)
  _rime_apply_diagnose_silence || log_warn "Could not update fcitx5's notification settings."

  log_info "Installed fcitx5 + RIME."
  log_info "Pick schemas / enable 雾凇拼音 with:  swkit rime configure   (or: swkit rime)"
  _rime_post_install_notes
}

do_remove() {
  if ! status >/dev/null 2>&1; then
    log_info "The RIME engine (fcitx5-rime) is not installed — nothing to remove."
    return 0
  fi
  apt_remove fcitx5-rime
  log_info "Removed the RIME engine (fcitx5-rime). Kept fcitx5 itself, your IM environment,"
  log_info "the fcitx5 autostart entry and your RIME data so other engines / a re-install keep working."
  log_info "To remove the whole framework too:  sudo apt remove fcitx5 'fcitx5-*'"
  log_info "  and:  rm -f ~/.config/autostart/org.fcitx.Fcitx5.desktop ~/.config/environment.d/ubuntu-setup-rime.conf"
}

# --- Configure -----------------------------------------------------------------

do_configure() {
  _rime_resolve_home || return 1
  _rime_load
  local want_deploy=0

  while (( $# > 0 )); do
    case "$1" in
      --recommended)
        SCHEMAS="luna_pinyin_simp luna_pinyin"; PAGE_SIZE=8; want_deploy=1; shift ;;
      --schemas)
        [[ $# -ge 2 ]] || { log_err "--schemas needs a space-separated list, e.g. \"luna_pinyin_simp luna_pinyin\"."; return 2; }
        SCHEMAS="$2"; shift 2 ;;
      --schemas=*) SCHEMAS="${1#--schemas=}"; shift ;;
      --default-schema)
        [[ $# -ge 2 ]] || { log_err "--default-schema needs a schema id."; return 2; }
        _rime_schema_id_valid "$2" || { log_err "Invalid schema id: $2"; return 2; }
        _rime_schema_set_default "$2"; shift 2 ;;
      --default-schema=*)
        _rime_schema_id_valid "${1#--default-schema=}" || { log_err "Invalid schema id."; return 2; }
        _rime_schema_set_default "${1#--default-schema=}"; shift ;;
      --page-size)
        if [[ $# -lt 2 ]] || ! _rime_pagesize_valid "${2:-}"; then log_err "--page-size needs an integer from 5 to 10."; return 2; fi
        PAGE_SIZE="$2"; shift 2 ;;
      --page-size=*)
        if ! _rime_pagesize_valid "${1#--page-size=}"; then log_err "--page-size needs an integer from 5 to 10."; return 2; fi
        PAGE_SIZE="${1#--page-size=}"; shift ;;
      --fuzzy)
        [[ $# -ge 2 ]] || { log_err "--fuzzy needs a space-separated list (or \"\" to clear), e.g. \"zh_z in_ing en_eng\"."; return 2; }
        FUZZY="$2"; shift 2 ;;
      --fuzzy=*) FUZZY="${1#--fuzzy=}"; shift ;;
      --silence-wayland-diagnose)
        [[ $# -ge 2 ]] || { log_err "--silence-wayland-diagnose needs on|off."; return 2; }
        case "$2" in
          on)  SILENCE_WAYLAND_DIAGNOSE=1 ;;
          off) SILENCE_WAYLAND_DIAGNOSE=0 ;;
          *)   log_err "--silence-wayland-diagnose needs on|off."; return 2 ;;
        esac
        shift 2 ;;
      --silence-wayland-diagnose=*)
        case "${1#*=}" in
          on)  SILENCE_WAYLAND_DIAGNOSE=1 ;;
          off) SILENCE_WAYLAND_DIAGNOSE=0 ;;
          *)   log_err "--silence-wayland-diagnose needs on|off."; return 2 ;;
        esac
        shift ;;
      --deploy) want_deploy=1; shift ;;
      *) log_err "Unknown configure option: $1"; usage; return 2 ;;
    esac
  done

  # Validate/sanitize the resolved schema list (drop empties / invalid ids, keep order).
  local s clean=""
  for s in $SCHEMAS; do
    if _rime_schema_id_valid "$s"; then clean="${clean:+$clean }$s"; else log_warn "Dropping invalid schema id: $s"; fi
  done
  [[ -n "$clean" ]] || clean="luna_pinyin_simp luna_pinyin"
  SCHEMAS="$clean"

  # Validate/sanitize the fuzzy-pair set (drop unknown keys, keep curated membership).
  local fk fclean=""
  for fk in $FUZZY; do
    if _rime_fuzzy_valid "$fk"; then fclean="${fclean:+$fclean }$fk"; else log_warn "Dropping unknown fuzzy pair: $fk"; fi
  done
  FUZZY="$fclean"

  _rime_save || { log_err "Failed to save preferences to $_R_PREF."; return 1; }
  _rime_render
  _rime_apply_diagnose_silence || log_warn "Could not update fcitx5's notification settings (notifications.conf)."
  log_info "RIME config written. Enabled schemas: $SCHEMAS (default: $(_rime_default_schema)); page size: $PAGE_SIZE; fuzzy: ${FUZZY:-(none)}."
  [[ "${SILENCE_WAYLAND_DIAGNOSE:-0}" == 1 ]] && log_info "fcitx5's GNOME-Wayland diagnose popup is silenced (takes effect at the next login)."
  _rime_warn_no_fuzzy_target
  if (( want_deploy )); then _rime_deploy; else log_info "Apply it with:  swkit rime deploy"; fi
  _rime_where_note
}

# --- Schema actions (parameterized; routed by kit_dispatch, reachable from ui) --

do_add_schema() {
  [[ $# -ge 1 ]] || { log_err "Usage: rime add-schema <schema-id>  (e.g. bopomofo)"; return 2; }
  _rime_schema_id_valid "$1" || { log_err "Invalid schema id: $1"; return 2; }
  _rime_resolve_home || return 1
  _rime_load
  if [[ "${RIME_ICE:-0}" == 1 ]]; then
    log_warn "雾凇拼音 (rime-ice) is active and owns the schema list; remove it first to manage schemas here."
    return 0
  fi
  _rime_schema_in "$1" && { log_info "Schema '$1' is already enabled."; return 0; }
  _rime_schema_add "$1"
  _rime_save; _rime_render
  log_info "Enabled schema '$1'. Enabled: $SCHEMAS"
  _rime_deploy
}

do_remove_schema() {
  [[ $# -ge 1 ]] || { log_err "Usage: rime remove-schema <schema-id>"; return 2; }
  _rime_resolve_home || return 1
  _rime_load
  _rime_schema_in "$1" || { log_info "Schema '$1' is not enabled — nothing to do."; return 0; }
  local remaining=0 s
  for s in $SCHEMAS; do [[ "$s" == "$1" ]] || remaining=$(( remaining + 1 )); done
  (( remaining >= 1 )) || { log_err "Refusing to remove the last enabled schema."; return 2; }
  _rime_schema_remove "$1"
  _rime_save; _rime_render
  log_info "Disabled schema '$1'. Enabled: $SCHEMAS"
  _rime_deploy
}

do_set_default_schema() {
  [[ $# -ge 1 ]] || { log_err "Usage: rime set-default-schema <schema-id>"; return 2; }
  _rime_schema_id_valid "$1" || { log_err "Invalid schema id: $1"; return 2; }
  _rime_resolve_home || return 1
  _rime_load
  _rime_schema_set_default "$1"
  _rime_save; _rime_render
  log_info "Default schema is now '$1'. Enabled: $SCHEMAS"
  _rime_deploy
}

# --- Fuzzy-pinyin actions (parameterized; routed by kit_dispatch, reachable from ui) ---

do_add_fuzzy() {
  [[ $# -ge 1 ]] || { log_err "Usage: rime add-fuzzy <pair>  (e.g. zh_z, n_l, in_ing). Pairs: ${_RIME_FUZZY[*]}"; return 2; }
  _rime_fuzzy_valid "$1" || { log_err "Unknown fuzzy pair: $1. Pairs: ${_RIME_FUZZY[*]}"; return 2; }
  _rime_resolve_home || return 1
  _rime_load
  _rime_fuzzy_in "$1" && { log_info "Fuzzy pair '$1' is already enabled."; return 0; }
  _rime_fuzzy_add "$1"
  _rime_save; _rime_render
  log_info "Enabled fuzzy pair '$1'. Enabled fuzzy: ${FUZZY:-(none)}"
  _rime_warn_no_fuzzy_target
  _rime_deploy
}

do_remove_fuzzy() {
  [[ $# -ge 1 ]] || { log_err "Usage: rime remove-fuzzy <pair>"; return 2; }
  _rime_fuzzy_valid "$1" || { log_err "Unknown fuzzy pair: $1. Pairs: ${_RIME_FUZZY[*]}"; return 2; }
  _rime_resolve_home || return 1
  _rime_load
  _rime_fuzzy_in "$1" || { log_info "Fuzzy pair '$1' is not enabled — nothing to do."; return 0; }
  _rime_fuzzy_remove "$1"
  _rime_save; _rime_render
  log_info "Disabled fuzzy pair '$1'. Enabled fuzzy: ${FUZZY:-(none)}"
  _rime_deploy
}

# --- 雾凇拼音 (rime-ice): manifest-based, reversible install -------------------

do_install_rime_ice() {
  _rime_resolve_home || return 1
  _rime_load
  have_cmd git || { log_err "git is required for rime-ice — run: swkit git install"; return 1; }
  _rime_where_note

  if [[ -d "$_R_ICE_CLONE/.git" ]]; then
    log_info "Updating the existing rime-ice clone…"
    ( cd "$_R_ICE_CLONE" && git pull --ff-only ) || log_warn "git pull failed — using the existing clone."
  else
    mkdir -p "$(dirname "$_R_ICE_CLONE")"
    git clone --depth 1 "$_RIME_ICE_REPO" "$_R_ICE_CLONE" || { log_err "Failed to clone rime-ice."; return 1; }
  fi

  mkdir -p "$_R_RIME_DIR" "$_R_PREF_DIR"
  # Remember what WE installed last time so a re-install doesn't back up our own files.
  local -A was_ours=()
  if [[ -f "$_R_ICE_MANIFEST" ]]; then
    local ln
    while IFS= read -r ln || [[ -n "$ln" ]]; do [[ -n "$ln" ]] && was_ours["$ln"]=1; done <"$_R_ICE_MANIFEST"
  fi

  : >"$_R_ICE_MANIFEST"
  local entry base
  for entry in "$_R_ICE_CLONE"/*; do
    [[ -e "$entry" ]] || continue
    base="$(basename "$entry")"
    case "$base" in .git|.github|*.md|LICENSE|.gitignore|.gitattributes) continue ;; esac
    if [[ -e "$_R_RIME_DIR/$base" && -z "${was_ours[$base]:-}" ]]; then
      backup_file "$_R_RIME_DIR/$base"
    fi
    rm -rf "${_R_RIME_DIR:?}/$base"
    cp -rf "$entry" "$_R_RIME_DIR/$base"
    printf '%s\n' "$base" >>"$_R_ICE_MANIFEST"
  done

  RIME_ICE=1; _rime_save
  _rime_render   # drop our schema_list (rime-ice owns it); retarget fuzzy onto rime_ice
  log_info "Installed 雾凇拼音 (rime-ice) into $_R_RIME_DIR."
  _rime_deploy
}

do_remove_rime_ice() {
  _rime_resolve_home || return 1
  _rime_load
  if [[ -f "$_R_ICE_MANIFEST" ]]; then
    local ln
    while IFS= read -r ln || [[ -n "$ln" ]]; do
      [[ -n "$ln" ]] || continue
      case "$ln" in /*|*..*) log_warn "Skipping unsafe manifest entry: $ln"; continue ;; esac
      rm -rf "${_R_RIME_DIR:?}/$ln"
    done <"$_R_ICE_MANIFEST"
    rm -f "$_R_ICE_MANIFEST"
    log_info "Removed rime-ice files from $_R_RIME_DIR."
  else
    log_info "rime-ice is not installed (no manifest) — nothing to remove."
  fi
  rm -rf "$_R_ICE_CLONE"
  RIME_ICE=0; _rime_save
  _rime_render   # restore the built-in schema_list; retarget fuzzy onto the luna_pinyin family
  _rime_deploy
}

# --- Interactive management screen --------------------------------------------

ui() {
  if ! ui_supported; then ui_default_menu; return 0; fi
  _rime_resolve_home || { ui_default_menu; return 0; }
  ui_begin || { ui_default_menu; return 0; }

  local sel=0 g
  while true; do
    [[ "${_UI_WINCH:-0}" == 1 ]] && { _UI_WINCH=0; ui_size; }
    _rime_load
    local installed=0 ver=""
    if status >/dev/null 2>&1; then installed=1; ver="$(fcitx5 --version 2>/dev/null | head -n1 || true)"; fi
    local envd_ok=0; [[ -f "$_R_ENVD" ]] && envd_ok=1
    local auto_ok=0; [[ -f "$_R_AUTOSTART" ]] && auto_ok=1
    local ice_on=0; [[ "${RIME_ICE:-0}" == 1 ]] && ice_on=1
    local silence_on=0; [[ "${SILENCE_WAYLAND_DIAGNOSE:-0}" == 1 ]] && silence_on=1
    local defschema; defschema="$(_rime_default_schema)"

    # ---- build display rows (parallel arrays: kind / id / label) ----
    local -a dkind=() did=() dlabel=()
    if _rime_no_display; then
      dkind+=(note); did+=(""); dlabel+=("$(_rime_t ui_ssh_note)")
      dkind+=(spacer); did+=(""); dlabel+=("")
    fi

    dkind+=(header); did+=(""); dlabel+=("$(_rime_t ui_sec_engine)")
    if (( ! installed )); then
      dkind+=(install); did+=(install); dlabel+=("$(ui_badge missing) $(ui_t install) fcitx5 + RIME")
    else
      dkind+=(envrow); did+=(""); dlabel+=("$(printf '%-22s %s' "$(_rime_t ui_im_environment)" "$( ((envd_ok)) && printf '%s %s' "$(ui_badge on)" "$(_rime_t ui_state_on)" || printf '%s %s' "$(ui_badge off)" "$(_rime_t ui_state_missing)")")")
      dkind+=(autorow); did+=(""); dlabel+=("$(printf '%-22s %s' "$(_rime_t ui_fcitx5_autostart)" "$( ((auto_ok)) && printf '%s %s' "$(ui_badge on)" "$(_rime_t ui_state_on)" || printf '%s %s' "$(ui_badge off)" "$(_rime_t ui_state_missing)")")")
      dkind+=(remove);  did+=(remove);  dlabel+=("${UI_ERR}${UI_CROSS}${UI_OFF} $(ui_t remove) $(_rime_t ui_rime_engine)")
    fi

    if (( installed )); then
      dkind+=(spacer); did+=(""); dlabel+=("")
      dkind+=(header); did+=(""); dlabel+=("$(_rime_t ui_sec_schemas)")
      if (( ice_on )); then
        dkind+=(note); did+=(""); dlabel+=("$(_rime_t ui_ice_owns_schemas)")
      else
        local key chk star desc
        for key in "${_RIME_CURATED[@]}"; do
          if _rime_schema_in "$key"; then chk="${UI_OK}${UI_CHK_ON}${UI_OFF}"; else chk="${UI_MUTED}${UI_CHK_OFF}${UI_OFF}"; fi
          star=""; [[ "$key" == "$defschema" ]] && star=" ${UI_INFO}★${UI_OFF}"
          desc="$(_rime_schema_desc "$key")"
          dkind+=(schema); did+=("$key"); dlabel+=("$(printf '%s %-20s %s%s' "$chk" "$key" "$desc" "$star")")
        done
        dkind+=(addschema); did+=(""); dlabel+=("${UI_ACCENT}＋${UI_OFF} $(_rime_t ui_add_schema_row)")
      fi

      dkind+=(spacer); did+=(""); dlabel+=("")
      dkind+=(header); did+=(""); dlabel+=("$(_rime_t ui_sec_options)")
      dkind+=(pagesize); did+=(pagesize); dlabel+=("$(printf '%-22s %s  %s' "$(_rime_t ui_candidates_per_page)" "$PAGE_SIZE" "$UI_ARROW")")
      dkind+=(diagnose); did+=(diagnose); dlabel+=("$(printf '%-30s %s' "$(_rime_t ui_silence_diagnose)" "$( ((silence_on)) && printf '%s %s' "$(ui_badge on)" "$(_rime_t ui_state_on)" || printf '%s %s' "$(ui_badge off)" "$(_rime_t ui_state_off)")")")
      dkind+=(note); did+=(""); dlabel+=("$(_rime_t ui_diagnose_note)")

      dkind+=(spacer); did+=(""); dlabel+=("")
      dkind+=(header); did+=(""); dlabel+=("$(_rime_t ui_sec_fuzzy)")
      dkind+=(note); did+=(""); dlabel+=("$(_rime_t ui_fuzzy_note)")
      [[ -z "$(_rime_fuzzy_targets)" ]] && { dkind+=(note); did+=(""); dlabel+=("$(_rime_t ui_fuzzy_no_target)"); }
      local fkey fchk fdesc
      for fkey in "${_RIME_FUZZY[@]}"; do
        if _rime_fuzzy_in "$fkey"; then fchk="${UI_OK}${UI_CHK_ON}${UI_OFF}"; else fchk="${UI_MUTED}${UI_CHK_OFF}${UI_OFF}"; fi
        fdesc="$(_rime_fuzzy_desc "$fkey")"
        dkind+=(fuzzy); did+=("$fkey"); dlabel+=("$(printf '%s %-10s %s' "$fchk" "$fkey" "$fdesc")")
      done

      dkind+=(spacer); did+=(""); dlabel+=("")
      dkind+=(header); did+=(""); dlabel+=("雾凇拼音 (rime-ice)")
      if (( ice_on )); then
        dkind+=(iceremove); did+=(""); dlabel+=("$(ui_badge on) $(_rime_t ui_ice_remove_row)")
      else
        dkind+=(iceinstall); did+=(""); dlabel+=("$(ui_badge off) $(_rime_t ui_ice_install_row)")
      fi

      dkind+=(spacer); did+=(""); dlabel+=("")
      dkind+=(header); did+=(""); dlabel+=("$(_rime_t ui_sec_actions)")
      dkind+=(deploy);  did+=(""); dlabel+=("$(ui_badge check) $(_rime_t ui_deploy_now)")
      dkind+=(recommend); did+=(""); dlabel+=("$(ui_badge check) $(_rime_t ui_apply_recommended)")
    fi

    local n=${#dkind[@]}
    (( sel < 0 )) && sel=0; (( sel >= n )) && sel=$(( n - 1 ))
    case "${dkind[$sel]}" in note|spacer|header|envrow|autorow)
      for (( g=0; g<n; g++ )); do sel=$(( (sel+1)%n )); case "${dkind[$sel]}" in note|spacer|header|envrow|autorow) ;; *) break ;; esac; done ;;
    esac

    # ---- render ----
    printf '\033[2J' >&"$_UI_FD"
    if (( installed )); then ui_header "RIME · input method" "${ver:-installed} $(ui_badge installed)"
    else ui_header "RIME · input method" "$(ui_t not_installed)"; fi
    local i row=3
    for (( i=0; i<n; i++ )); do
      case "${dkind[$i]}" in
        spacer) : ;;
        note)   ui_move "$row" 2; printf '\033[K%s%s%s' "$UI_MUTED" "${dlabel[$i]}" "$UI_OFF" >&"$_UI_FD" ;;
        header) ui_move "$row" 2; printf '\033[K%s%s%s' "$UI_ACCENT$UI_BOLD" "${dlabel[$i]}" "$UI_OFF" >&"$_UI_FD" ;;
        envrow|autorow) ui_move "$row" 4; printf '\033[K%s' "${dlabel[$i]}" >&"$_UI_FD" ;;
        *)      ui_row "$row" "$i" "$sel" "${dlabel[$i]}" ;;
      esac
      (( row++ ))
    done
    ui_footer "$(_rime_t ui_footer_hints)"

    # ---- input ----
    ui_read_key
    case "$UI_KEY" in
      up|k)   for (( g=0; g<n; g++ )); do sel=$(( (sel-1+n)%n )); case "${dkind[$sel]}" in note|spacer|header|envrow|autorow) ;; *) break ;; esac; done ;;
      down|j) for (( g=0; g<n; g++ )); do sel=$(( (sel+1)%n ));   case "${dkind[$sel]}" in note|spacer|header|envrow|autorow) ;; *) break ;; esac; done ;;
      space)
        case "${dkind[$sel]}" in
          schema)
            local id="${did[$sel]}"
            if _rime_schema_in "$id"; then
              ui_run "$(_rime_t ui_run_disable_schema) $id · rime" -- "$0" remove-schema "$id"
            else
              ui_run "$(_rime_t ui_run_enable_schema) $id · rime" -- "$0" add-schema "$id"
            fi ;;
          fuzzy)
            local fid="${did[$sel]}"
            if _rime_fuzzy_in "$fid"; then
              ui_run "$(_rime_t ui_run_disable_fuzzy) $fid · rime" -- "$0" remove-fuzzy "$fid"
            else
              ui_run "$(_rime_t ui_run_enable_fuzzy) $fid · rime" -- "$0" add-fuzzy "$fid"
            fi ;;
          diagnose)
            if (( silence_on )); then
              ui_run "$(_rime_t ui_run_silence) · rime" -- "$0" configure --silence-wayland-diagnose off
            else
              ui_run "$(_rime_t ui_run_silence) · rime" -- "$0" configure --silence-wayland-diagnose on
            fi ;;
        esac ;;
      d|D)
        [[ "${dkind[$sel]}" == schema ]] && ui_run "$(_rime_t ui_run_set_default_schema) ${did[$sel]} · rime" -- "$0" set-default-schema "${did[$sel]}" ;;
      a|A)
        if (( installed )) && (( ! ice_on )); then
          if ui_input "$(_rime_t ui_prompt_schema_id)" ""; then
            [[ -n "$UI_INPUT" ]] && ui_run "$(_rime_t ui_run_add_schema) $UI_INPUT · rime" -- "$0" add-schema "$UI_INPUT"
          fi
        fi ;;
      enter)
        case "${dkind[$sel]}" in
          install)    ui_run "$(ui_t install) fcitx5 + RIME" -- "$0" install ;;
          remove)     ui_confirm "$(_rime_t ui_confirm_remove_engine)" n && ui_run "$(ui_t remove) $(_rime_t ui_rime_engine)" -- "$0" remove ;;
          schema)
            local id="${did[$sel]}"
            if _rime_schema_in "$id"; then
              ui_run "$(_rime_t ui_run_disable_schema) $id · rime" -- "$0" remove-schema "$id"
            else
              ui_run "$(_rime_t ui_run_enable_schema) $id · rime" -- "$0" add-schema "$id"
            fi ;;
          addschema)
            if ui_input "$(_rime_t ui_prompt_schema_id)" ""; then
              [[ -n "$UI_INPUT" ]] && ui_run "$(_rime_t ui_run_add_schema) $UI_INPUT · rime" -- "$0" add-schema "$UI_INPUT"
            fi ;;
          fuzzy)
            local fid="${did[$sel]}"
            if _rime_fuzzy_in "$fid"; then
              ui_run "$(_rime_t ui_run_disable_fuzzy) $fid · rime" -- "$0" remove-fuzzy "$fid"
            else
              ui_run "$(_rime_t ui_run_enable_fuzzy) $fid · rime" -- "$0" add-fuzzy "$fid"
            fi ;;
          pagesize)
            if ui_input "$(_rime_t ui_prompt_page_size)" "$PAGE_SIZE"; then
              [[ -n "$UI_INPUT" ]] && ui_run "$(_rime_t ui_run_set_page_size) · rime" -- "$0" configure --page-size "$UI_INPUT"
            fi ;;
          diagnose)
            if (( silence_on )); then
              ui_run "$(_rime_t ui_run_silence) · rime" -- "$0" configure --silence-wayland-diagnose off
            else
              ui_run "$(_rime_t ui_run_silence) · rime" -- "$0" configure --silence-wayland-diagnose on
            fi ;;
          iceinstall) ui_confirm "$(_rime_t ui_confirm_install_ice)" y && ui_run "$(_rime_t ui_run_install_ice) · rime" -- "$0" install-rime-ice ;;
          iceremove)  ui_confirm "$(_rime_t ui_confirm_remove_ice)" n && ui_run "$(_rime_t ui_run_remove_ice) · rime" -- "$0" remove-rime-ice ;;
          deploy)     ui_run "$(_rime_t ui_run_deploy) · rime" -- "$0" deploy ;;
          recommend)  ui_run "$(_rime_t ui_run_apply_recommended) · rime" -- "$0" configure --recommended ;;
        esac ;;
      q|Q|esc|backspace) break ;;
    esac
  done
  ui_end
  return 0
}

usage() {
  cat <<EOF
Usage: ${0##*/} <command>

RIME input method on the fcitx5 framework. Installs fcitx5 + the RIME engine + frontends via
apt, selects fcitx5 (im-config), and writes a managed IM environment + RIME schema patch —
your own files are backed up before any change. RIME/fcitx5 is a desktop input method: over
SSH/headless these settings apply where the desktop runs, after the next login.

  install              Install fcitx5 + RIME (idempotent; converges config on re-run)
  remove               Uninstall the RIME engine (keeps fcitx5, IM env and your RIME data)
  configure [opts]     Set schemas / page size; with NO opts writes the conservative baseline.
                         --recommended           简体拼音优先 + page size 8 + deploy
                         --schemas "a b c"       enabled schemas (first is the default)
                         --default-schema <id>   make <id> the default (moves it first)
                         --page-size <5-10>      candidates shown per page
                         --fuzzy "a b c"         fuzzy-pinyin pairs (use "" to clear)
                         --silence-wayland-diagnose on|off
                                                 hide fcitx5's GNOME-Wayland diagnose popup
                         --deploy                redeploy RIME afterwards
  add-schema <id>      Enable one schema by id (curated or any with data present)
  remove-schema <id>   Disable one schema (never the last one)
  set-default-schema <id>   Make <id> the default schema
  add-fuzzy <pair>     Enable a fuzzy-pinyin pair (written to each active pinyin schema's custom)
  remove-fuzzy <pair>  Disable a fuzzy-pinyin pair
  install-rime-ice     Install 雾凇拼音 (rime-ice) — reversible, manifest-tracked, user-space
  remove-rime-ice      Remove rime-ice and restore the built-in schemas
  deploy               Ask a running fcitx5 to reload/redeploy RIME (no-op note if headless)
  status               Print the engine version if installed; exit 0 iff installed
  ui                   Open the interactive manager (needs a terminal)
  meta                 Print machine-readable metadata (for the TUI / swkit list)
  help                 Show this help

Curated schemas: ${_RIME_CURATED[*]}
Fuzzy pairs:     ${_RIME_FUZZY[*]}
  Fuzzy pinyin (模糊音) tolerates easily-confused initials/finals (zh↔z, n↔l, in↔ing…). It is a
  per-schema speller/algebra feature: pairs are appended to each active pinyin schema's
  <schema>.custom.yaml (rime_ice when 雾凇拼音 is on, else the luna_pinyin family) — NOT to the
  global default.custom.yaml. More pairs trade precision for tolerance.
EOF
}

kit_dispatch "$@"
